### ISSUE TITLE
Add basic installation and usage hints to README

### ISSUE THREAD

**Issue by hjoukl** [simon-w19/sw-datarest#3]
README.md should contain some basic information how to install and use sw-datarest imho.

E.g.

    pip install git+https://github.com/simon-w19/sw-datarest

(as long as it's not published on PyPI9)

and maybe a little example walkthrough, with a very basic CSV input file example, the SQLite DB creation  plus matching YAML configurations, both for database and the tableschema "profiles".

**Comment by simon-w19** [comment]
Thanks for the input. Added it to README.md
